"""Sincronizar modelos con la BD

Revision ID: 1af43da3db65
Revises: d957cfe71dd7
Create Date: 2025-02-03 15:51:52.226435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1af43da3db65'
down_revision: Union[str, None] = 'd957cfe71dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_schedules', 'result')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_schedules', sa.Column('result', sa.VARCHAR(length=130), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
