"""Modify data types and field sizes in student table

Revision ID: 28e107814f3e
Revises: 6bd412debd43
Create Date: 2025-01-27 00:47:34.786228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28e107814f3e'
down_revision: Union[str, None] = '6bd412debd43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'description')
    op.add_column('students', sa.Column('names', sa.String(length=70), nullable=False))
    op.add_column('students', sa.Column('surnames', sa.String(length=70), nullable=False))
    op.add_column('students', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('students', 'photo_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_column('students', 'academic_grade')
    op.drop_column('students', 'first_name')
    op.drop_column('students', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('academic_grade', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.alter_column('students', 'photo_url',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('students', 'description')
    op.drop_column('students', 'surnames')
    op.drop_column('students', 'names')
    op.add_column('roles', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
