"""Add temporary_password field to users table

Revision ID: 53608c7d277e
Revises: f78e965fed1c
Create Date: 2025-01-12 06:32:55.533626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53608c7d277e'
down_revision: Union[str, None] = 'f78e965fed1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('users', sa.Column('temporary_password', sa.Boolean(), nullable=True))
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.drop_column('users', 'temporary_password')
    op.alter_column('roles', 'description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
