"""Remove unique constraint from student ID field

Revision ID: 5a17ac5efa47
Revises: e9c11a8be7ac
Create Date: 2025-01-31 18:14:50.364398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a17ac5efa47'
down_revision: Union[str, None] = 'e9c11a8be7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('students_identification_key', 'students', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('students_identification_key', 'students', ['identification'])
    # ### end Alembic commands ###
