"""Arreglo de la Base 2e dicion

Revision ID: 60cb44da4077
Revises: a797f70eaa03
Create Date: 2025-02-03 15:30:24.536684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60cb44da4077'
down_revision: Union[str, None] = 'a797f70eaa03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
