"""Add fields for logical deletion and adjust data in student table

Revision ID: 6bd412debd43
Revises: 2d9ef86d2448
Create Date: 2025-01-26 12:20:27.780568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bd412debd43'
down_revision: Union[str, None] = '2d9ef86d2448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judges', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('representatives', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('identification_filename', sa.String(length=150), nullable=False))
    op.add_column('students', sa.Column('authorization_filename', sa.String(length=150), nullable=False))
    op.add_column('students', sa.Column('enrollment_filename', sa.String(length=150), nullable=False))
    op.add_column('students', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.alter_column('students', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=15),
               nullable=False)
    op.drop_column('students', 'identification_url')
    op.drop_column('students', 'enrollment_url')
    op.drop_column('students', 'authorization_url')
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.add_column('students', sa.Column('authorization_url', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('enrollment_url', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('identification_url', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('students', 'status',
               existing_type=sa.String(length=15),
               type_=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('students', 'is_deleted')
    op.drop_column('students', 'enrollment_filename')
    op.drop_column('students', 'authorization_filename')
    op.drop_column('students', 'identification_filename')
    op.drop_column('representatives', 'is_deleted')
    op.drop_column('judges', 'is_deleted')
    # ### end Alembic commands ###
