"""Add table for student registration in sports events

Revision ID: 7810071939ed
Revises: b75560c79cd7
Create Date: 2025-01-30 09:38:23.909491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7810071939ed'
down_revision: Union[str, None] = 'b75560c79cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_categories_category_id', table_name='categories')
    op.drop_index('ix_eventparticipant_id_event', table_name='eventparticipant')
    op.drop_index('ix_events_event_id', table_name='events')
    op.drop_index('ix_sports_sport_id', table_name='sports')
    op.drop_column('students', 'description')
    op.drop_column('students', 'status')
    op.drop_index('ix_venues_event_id_event', table_name='venues_event')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_venues_event_id_event', 'venues_event', ['id_event'], unique=False)
    op.add_column('students', sa.Column('status', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('ix_sports_sport_id', 'sports', ['sport_id'], unique=False)
    op.create_index('ix_events_event_id', 'events', ['event_id'], unique=False)
    op.create_index('ix_eventparticipant_id_event', 'eventparticipant', ['id_event'], unique=False)
    op.create_index('ix_categories_category_id', 'categories', ['category_id'], unique=False)
    # ### end Alembic commands ###
