"""Merge sports event management and student management features

Revision ID: 91f2e05c0600
Revises: 28e107814f3e
Create Date: 2025-01-28 17:50:05.569607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f2e05c0600'
down_revision: Union[str, None] = '28e107814f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categories_category_id'), 'categories', ['category_id'], unique=False)
    op.add_column('events', sa.Column('category_id', sa.Integer(), nullable=False))
    op.alter_column('events', 'sport_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=False)
    op.create_foreign_key(None, 'events', 'categories', ['category_id'], ['category_id'])
    op.create_index(op.f('ix_sports_sport_id'), 'sports', ['sport_id'], unique=False)
    op.alter_column('sports_venues', 'sport_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('sports_venues', 'status')
    op.alter_column('students', 'representative_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('students', 'gender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('students', 'academic_year_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('workshops', sa.Column('event_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'workshops', 'events', ['event_id'], ['event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workshops', type_='foreignkey')
    op.drop_column('workshops', 'event_id')
    op.alter_column('students', 'academic_year_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('students', 'gender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('students', 'representative_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('sports_venues', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('sports_venues', 'sport_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_sports_sport_id'), table_name='sports')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.alter_column('events', 'sport_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('events', 'category_id')
    op.drop_index(op.f('ix_categories_category_id'), table_name='categories')
    # ### end Alembic commands ###
