"""Arreglo de la Base

Revision ID: a797f70eaa03
Revises: b75560c79cd7
Create Date: 2025-02-03 15:21:49.891192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a797f70eaa03'
down_revision: Union[str, None] = 'b75560c79cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('disciplines_sport_id_fkey', 'disciplines', type_='foreignkey')
    op.drop_column('disciplines', 'sport_id')
    op.add_column('team_schedules', sa.Column('result', sa.String(length=130), nullable=False))
    op.add_column('team_schedules', sa.Column('discipline_id', sa.Integer(), nullable=True))
    op.drop_constraint('team_schedules_events_fk', 'team_schedules', type_='foreignkey')
    op.create_foreign_key(None, 'team_schedules', 'disciplines', ['discipline_id'], ['discipline_id'])
    op.drop_column('team_schedules', 'event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_schedules', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'team_schedules', type_='foreignkey')
    op.create_foreign_key('team_schedules_events_fk', 'team_schedules', 'events', ['event_id'], ['event_id'])
    op.drop_column('team_schedules', 'discipline_id')
    op.drop_column('team_schedules', 'result')
    op.add_column('disciplines', sa.Column('sport_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('disciplines_sport_id_fkey', 'disciplines', 'sports', ['sport_id'], ['sport_id'])
    # ### end Alembic commands ###
