"""Tablas para participantes y escenarios con eventos 2da version

Revision ID: b75560c79cd7
Revises: c1e16fc996bf
Create Date: 2025-01-28 21:02:17.718937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b75560c79cd7'
down_revision: Union[str, None] = 'c1e16fc996bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventparticipant',
    sa.Column('id_event', sa.Integer(), nullable=False),
    sa.Column('id_educational_institution', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_educational_institution'], ['educational_institutions.institution_id'], ),
    sa.ForeignKeyConstraint(['id_event'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('id_event', 'id_educational_institution')
    )
    op.create_index(op.f('ix_eventparticipant_id_event'), 'eventparticipant', ['id_event'], unique=False)
    op.create_table('venues_event',
    sa.Column('id_event', sa.Integer(), nullable=False),
    sa.Column('id_venue', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_event'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['id_venue'], ['sports_venues.venue_id'], ),
    sa.PrimaryKeyConstraint('id_event', 'id_venue')
    )
    op.create_index(op.f('ix_venues_event_id_event'), 'venues_event', ['id_event'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venues_event_id_event'), table_name='venues_event')
    op.drop_table('venues_event')
    op.drop_index(op.f('ix_eventparticipant_id_event'), table_name='eventparticipant')
    op.drop_table('eventparticipant')
    # ### end Alembic commands ###
