"""Tablas para eventos y escenarios con eventos

Revision ID: c1e16fc996bf
Revises: 91f2e05c0600
Create Date: 2025-01-28 20:55:26.851207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e16fc996bf'
down_revision: Union[str, None] = '91f2e05c0600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
