"""Table Teams

Revision ID: c34ba3b90bf2
Revises: 1af43da3db65
Create Date: 2025-02-03 16:03:23.594011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c34ba3b90bf2'
down_revision: Union[str, None] = '1af43da3db65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_schedules', sa.Column('event_id', sa.Integer(), nullable=True))
    op.drop_constraint('team_schedules_discipline_id_fkey', 'team_schedules', type_='foreignkey')
    op.create_foreign_key(None, 'team_schedules', 'events', ['event_id'], ['event_id'])
    op.drop_column('team_schedules', 'discipline_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_schedules', sa.Column('discipline_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'team_schedules', type_='foreignkey')
    op.create_foreign_key('team_schedules_discipline_id_fkey', 'team_schedules', 'disciplines', ['discipline_id'], ['discipline_id'])
    op.drop_column('team_schedules', 'event_id')
    # ### end Alembic commands ###
