"""Build complete database

Revision ID: f78e965fed1c
Revises: e917b03ffaf1
Create Date: 2024-12-15 13:49:54.839256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78e965fed1c'
down_revision: Union[str, None] = 'e917b03ffaf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('academic_year_id')
    )
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('tournament_type', sa.String(length=50), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('educational_institutions',
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('institution_id')
    )
    op.create_table('genders',
    sa.Column('gender_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('gender_id')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('sports',
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('sport_id')
    )
    op.create_table('workshops',
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('workshop_id')
    )
    op.create_table('disciplines',
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allowed_gender', sa.String(length=30), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.sport_id'], ),
    sa.PrimaryKeyConstraint('discipline_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('registration_start_date', sa.Date(), nullable=True),
    sa.Column('registration_end_date', sa.Date(), nullable=True),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.sport_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('sports_venues',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.sport_id'], ),
    sa.PrimaryKeyConstraint('venue_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('judges',
    sa.Column('judge_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('judge_id')
    )
    op.create_table('representatives',
    sa.Column('representative_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['educational_institutions.institution_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('representative_id')
    )
    op.create_table('security_codes',
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('code_id')
    )
    op.create_table('workshop_attendance',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.workshop_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'workshop_id')
    )
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('identification', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('academic_grade', sa.String(length=10), nullable=False),
    sa.Column('blood_type', sa.String(length=3), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=False),
    sa.Column('identification_url', sa.Text(), nullable=False),
    sa.Column('authorization_url', sa.Text(), nullable=False),
    sa.Column('enrollment_url', sa.Text(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('representative_id', sa.Integer(), nullable=True),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.academic_year_id'], ),
    sa.ForeignKeyConstraint(['gender_id'], ['genders.gender_id'], ),
    sa.ForeignKeyConstraint(['representative_id'], ['representatives.representative_id'], ),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('identification')
    )
    op.create_table('team_schedules',
    sa.Column('team_schedule_id', sa.Integer(), nullable=False),
    sa.Column('encounter_date', sa.DateTime(), nullable=False),
    sa.Column('result', sa.String(length=130), nullable=False),
    sa.Column('institution_id1', sa.Integer(), nullable=True),
    sa.Column('institution_id2', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.Column('judge_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.discipline_id'], ),
    sa.ForeignKeyConstraint(['institution_id1'], ['educational_institutions.institution_id'], ),
    sa.ForeignKeyConstraint(['institution_id2'], ['educational_institutions.institution_id'], ),
    sa.ForeignKeyConstraint(['judge_id'], ['judges.judge_id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['sports_venues.venue_id'], ),
    sa.PrimaryKeyConstraint('team_schedule_id')
    )
    op.create_table('basketball_results',
    sa.Column('basketball_result_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('rebounds', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('team_schedule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['team_schedule_id'], ['team_schedules.team_schedule_id'], ),
    sa.PrimaryKeyConstraint('basketball_result_id')
    )
    op.create_table('football_results',
    sa.Column('football_result_id', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('team_schedule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['team_schedule_id'], ['team_schedules.team_schedule_id'], ),
    sa.PrimaryKeyConstraint('football_result_id')
    )
    op.create_table('individual_schedules',
    sa.Column('in_schedule_id', sa.Integer(), nullable=False),
    sa.Column('schedule_date', sa.DateTime(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('judge_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.discipline_id'], ),
    sa.ForeignKeyConstraint(['judge_id'], ['judges.judge_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['sports_venues.venue_id'], ),
    sa.PrimaryKeyConstraint('in_schedule_id')
    )
    op.create_table('athletics_results',
    sa.Column('athletics_result_id', sa.Integer(), nullable=False),
    sa.Column('time_elapsed', sa.Interval(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('in_schedule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['in_schedule_id'], ['individual_schedules.in_schedule_id'], ),
    sa.PrimaryKeyConstraint('athletics_result_id')
    )
    op.create_table('chess_results',
    sa.Column('chess_result_id', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('in_schedule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['in_schedule_id'], ['individual_schedules.in_schedule_id'], ),
    sa.PrimaryKeyConstraint('chess_result_id')
    )
    op.drop_table('role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='role_pkey')
    )
    op.drop_table('chess_results')
    op.drop_table('athletics_results')
    op.drop_table('individual_schedules')
    op.drop_table('football_results')
    op.drop_table('basketball_results')
    op.drop_table('team_schedules')
    op.drop_table('students')
    op.drop_table('workshop_attendance')
    op.drop_table('security_codes')
    op.drop_table('representatives')
    op.drop_table('judges')
    op.drop_table('users')
    op.drop_table('sports_venues')
    op.drop_table('events')
    op.drop_table('disciplines')
    op.drop_table('workshops')
    op.drop_table('sports')
    op.drop_table('roles')
    op.drop_table('genders')
    op.drop_table('educational_institutions')
    op.drop_table('categories')
    op.drop_table('academic_years')
    # ### end Alembic commands ###
