from src.database.base_class import Base
from src.models.role import Role
from src.models.user import User
from src.models.security_code import SecurityCode
from src.models.workshop import Workshop
from src.models.workshop_attendance import WorkshopAttendance
from src.models.educational_institution import EducationalInstitution
from src.models.representative import Representative
from src.models.sport import Sport
from src.models.sports_venue import SportsVenue
from src.models.category import Category
from src.models.discipline import Discipline
from src.models.event import Event
from src.models.gender import Gender
from src.models.academic_year import AcademicYear
from src.models.student import Student
from src.models.judge import Judge
from src.models.team_schedule import TeamSchedule
from src.models.individual_schedule import IndividualSchedule
from src.models.basketball_result import BasketballResult
from src.models.football_result import FootballResult
from src.models.chess_result import ChessResult
from src.models.athletics_result import AthleticsResult