MAX_FILE_SIZE = 10 * 1024 * 1024
MAX_IMAGE_SIZE = 5 * 1024 * 1024
ALLOWED_IMAGE_TYPES = ["image/png", "image/jpeg"]
ALLOWED_DOCUMENT_TYPES = ["application/pdf", "image/png", "image/jpeg"]

MAX_SOCCER_PLAYERS = 15
MIN_SOCCER_PLAYERS = 11

MAX_BASKETBALL_PLAYERS = 12
MIN_BASKETBALL_PLAYERS = 5
